[QA-3033] Pytest reruns with fixtures invalidation
datarobot/pytest-rerunfailures pull request #1
Opened 2018-03-29 15:14 UTC by oiefimenko

## Rationally
Current fork aimed to improve rerun approach so it will be suitable for tests with module and session scoped fixtures.

## Changes
Added all scoped fixtures invalidation for current test item in case of test failure before rerun occurs.
Plugin able to track all related fixtures: direct injects, autouse, usefixture mark.
Fixtures invalidated gracefully with executing finalizer.

## Testing
The same functionality was run against current functional splits and reruns helped for several (about 8) tests to pass during runs:
https://jenkins.hq.datarobot.com/job/paralleled_functional_executor_TEST/307/
https://jenkins.hq.datarobot.com/job/paralleled_functional_executor_TEST/308/
https://jenkins.hq.datarobot.com/job/paralleled_functional_executor_TEST/309/
https://jenkins.hq.datarobot.com/job/paralleled_functional_executor_TEST/310/

## Jira
https://datarobot.atlassian.net/browse/QA-3033

2018-03-29 16:22 UTC, lyapun requested changes
```
07:15:00 tests/functional/apitests/test_blueprint_chart.py::test_blueprint_chart_from_prime RERUN [ 13%]
07:15:37 tests/functional/apitests/test_blueprint_chart.py::test_blueprint_chart_from_prime ERROR [ 13%]
```

Why RERUN logged? So we trying to rerun test twice? One right after fail and one more time at the end after cleaning fixtures?

Does it work, as we discussed?

1. Collect failed tests.
2. Clear all fixtures.
3. Rerun failed tests.

As I understand - no? I think cleaning all fixtures for every fail - is too expensive.

2018-03-29 16:22 UTC, lyapun commented on CHANGES.rst
> +0.9 (2018-03-29)
why version is 0.9?

2018-03-29 16:22 UTC, lyapun commented on CHANGES.rst
> -  (Logging intermediate results will finish the test rather rerunning it.)
why need to remove all original history?

2018-03-29 16:22 UTC, lyapun commented on pytest_cleanrerun.py
> +                fixtures = set(item.fixturenames)
won't be here a problem when different fixtures have the same name (but defined in different places)?

2018-03-29 21:28 UTC, oiefimenko commented on pytest_cleanrerun.py
> +                fixtures = set(item.fixturenames)
No, it won't. 
On line 159 we request fixture definition object from fixture manager with providing current test item which return us definitions related only to current item scope.
```
for fixtdef in fixturemanager.getfixturedefs(fixt, item.nodeid) or []:
```

Also by this we unload only those fixtures, which are related only for current test.

2018-03-29 21:31 UTC, oiefimenko commented on CHANGES.rst
> -  (Logging intermediate results will finish the test rather rerunning it.)
We had to rename package to avoid conflicts, so I removed history from package with previous name to not mislead. But it could be easily returned.

2018-03-29 21:32 UTC, oiefimenko commented on CHANGES.rst
> +0.9 (2018-03-29)
I set it as 0.9 as we probably could improve or add anything to logic of fork.
I though it could be to self-confident to set 1.0 version from scratch.

2018-03-29 21:45 UTC, oiefimenko commented
```
Why RERUN logged? So we trying to rerun test twice? One right after fail and one more time at the end after cleaning fixtures?
```
RERUN status means that this test failed and rescheduled for rerun. So in this example it actually reruns only once.

```
Does it work, as we discussed?

Collect failed tests.
Clear all fixtures.
Rerun failed tests.
As I understand - no? I think cleaning all fixtures for every fail - is too expensive.
```
Currently it is working in straightforward way of retrying after failure for several reasons:
1. We do not unload all fixtures. We unload only those fixtures chains which are injected in current test Item scope. So from perspective of unloading/loading all fixtures it would be the same in terms of operation costs.
2. With current approach we ensure that each test should work from fresh start (which is good from my perspective).
3. If several tests fails in a row because of the same mutations (and provides such) current approach ensure isolated execution of each of them.
4. Pytest is event driven inside and we require some additional hacks to overwrite already published events for different listeners. Overall this approach requires more coding because of some pytest specifics.

@burkestar @andrew-qa What are yours opinions on it?

2018-03-30 06:14 UTC, lyapun commented
> 1. We do not unload all fixtures. We unload only those fixtures chains which are injected in current test Item scope. So from perspective of unloading/loading all fixtures it would be the same in terms of operation costs.

I'm not completely agree with this point, because if used fixture is something like `completed_project` - it will be pretty long to initialize it again for every fail.

Also, I'm worried about tests inside one module that depends on each other. Like one test requires some other test to be executed before it (we have some of those). Clearing fixtures during test run might broke them.

But, I'm fine to start with simpler solution, and see how well it will work, if @burkestar and @andrew-qa agreed with you that it's good enough.

2018-03-30 08:53 UTC, andrew-qa commented
I also prefer to have retries at the end, when we have a full list of failures. It allows us to do different optimizations and just looks more logical for me.
But it will require additional efforts to implement. And we spent a lot of time already, so I prefer to move forward. This change looks quite easy to apply and easy to revert if needed.
Test launches show that it allows retrying test properly. Also, overhead on fixtures is still less than the duration of full job retry.
So I support this change. We will get results and make further decisions based on them.

2018-03-30 08:53 UTC, andrew-qa approved these changes

2018-03-30 08:55 UTC, lyapun approved these changes
Ok, let's do it.

2018-03-30 09:56 UTC, merged

2018-03-30 13:27 UTC, burkestar commented on CHANGES.rst
> +0.9 (2018-03-29)
If we're forking to a new project, we should probably just blow away all the history in the changelog and start from 0.1.

2018-03-30 13:31 UTC, burkestar commented on pytest_cleanrerun.py
> +                fixtures = set(item.fixturenames)
We should probably prevent fixtures sharing the same name anyways.  I think in DataRobot conftest for fixture initialization phase, we should detect and fail if the same name will be reused.